apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: al-mizan
  labels:
    app: notification-service
data:
  NODE_ENV: "production"
  PORT: "8010"
  API_PREFIX: "notification-service/v1"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  RABBITMQ_EXCHANGE: "al_mizan_events"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_TTL: "3600"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  INFOBIP_BASE_URL: "https://api.infobip.com"
  SMS_SENDER_ID: "ALMIZAN"
